import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import { SnapshotManager } from '../dist/st/snapshots.js';
const hash = x => createHash('sha256').update(x).digest('hex');

test('file snapshots have budgets, do not copy siblings, and require versioned recovery', async t => {
    const root = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'nora-mcp-snapshot-')));
    t.after(() => fs.rm(root, { recursive: true, force: true }));
    const file = path.join(root, 'settings.json'); const other = path.join(root, 'chat.jsonl');
    await fs.writeFile(file, 'before'); await fs.writeFile(other, 'untouched');
    const manager = new SnapshotManager({ projectRoot: root, stRoot: root, userDataRoot: root, configPath: file, snapshotRoot: path.join(root, 'snapshots') }, { maxSnapshots: 2, maxTotalBytes: 100, maxSnapshotBytes: 20 });
    await assert.rejects(manager.create(), /Explicit/);
    await assert.rejects(manager.create('all', [root]));
    const first = await manager.create('one', [file]);
    assert.equal(first.files.length, 1);
    assert.equal(await fs.readFile(path.join(first.root, '0.bin'), 'utf8'), 'before');
    await fs.writeFile(file, 'after');
    await assert.rejects(manager.rollback(first.id), /current hashes/);
    await assert.rejects(manager.rollback(first.id, { [file]: hash('wrong') }), /changed/);
    await manager.rollback(first.id, { [file]: hash('after') });
    assert.equal(await fs.readFile(file, 'utf8'), 'before');
    assert.equal(await fs.readFile(other, 'utf8'), 'untouched');
    await manager.create('two', [file]); await manager.create('three', [file]);
    assert.equal((await manager.list()).length, 2);
    await assert.rejects(manager.rollback('../outside', {}), /Invalid snapshot ID/);
    await fs.writeFile(file, 'x'.repeat(21));
    await assert.rejects(manager.create('large', [file]), /budget/);
    assert.equal((await manager.list()).length, 2);
});
